# netlify.toml
[build]
  publish = "public"
  functions = "lambda"
  command = "npm run build"

  [build.environment]
  NODE_VERSION = "14"  # Set your desired Node.js version

[dev]
  port = 8888
  targetPort = 8080
  autoLaunch = true
